

DROP_TABLE_RAW = """
DROP TABLE IF EXISTS diabetes_raw

"""

DROP_TABLE_CLEAN = """
DROP TABLE IF EXISTS diabetes_clean

"""
DROP_TABLE_TRAIN = """
DROP TABLE IF EXISTS diabetes_clean_train

"""

DROP_TABLE_TEST = """
DROP TABLE IF EXISTS diabetes_clean_test

"""

DROP_TABLE_VAL = """
DROP TABLE IF EXISTS diabetes_clean_val

"""

CREATE_TABLE_RAW = """ CREATE TABLE IF NOT EXISTS diabetes_raw (A1Cresult VARCHAR(20) NULL,
    acarbose VARCHAR(10) NULL,
    acetohexamide VARCHAR(10) NULL,
    admission_source_id INT NULL,
    admission_type_id INT NULL,
    age VARCHAR(10) NULL,
    cambio VARCHAR(10) NULL,
    chlorpropamide VARCHAR(10) NULL,
    citoglipton VARCHAR(10) NULL,
    diabetesMed VARCHAR(10) NULL,
    diag_1 VARCHAR(10) NULL,
    diag_2 VARCHAR(10) NULL,
    diag_3 VARCHAR(10) NULL,
    discharge_disposition_id INT NULL,
    encounter_id BIGINT NULL,
    examide VARCHAR(10) NULL,
    gender VARCHAR(50) NULL,
    glimepiride VARCHAR(10) NULL,
    glimepiride_pioglitazone VARCHAR(10) NULL,
    glipizide VARCHAR(10) NULL,
    glipizide_metformin VARCHAR(10) NULL,
    glyburide VARCHAR(10) NULL,
    glyburide_metformin VARCHAR(10) NULL,
    insulin VARCHAR(10) NULL,
    max_glu_serum VARCHAR(20) NULL,
    medical_specialty VARCHAR(100) NULL,
    metformin VARCHAR(10) NULL,
    metformin_pioglitazone VARCHAR(10) NULL,
    metformin_rosiglitazone VARCHAR(10) NULL,
    miglitol VARCHAR(10) NULL,
    nateglinide VARCHAR(10) NULL,
    num_lab_procedures INT NULL,
    num_medications INT NULL,
    num_procedures INT NULL,
    number_diagnoses INT NULL,
    number_emergency INT NULL,
    number_inpatient INT NULL,
    number_outpatient INT NULL,
    patient_nbr BIGINT NULL,
    payer_code VARCHAR(10) NULL,
    pioglitazone VARCHAR(10) NULL,
    race VARCHAR(50) NULL,
    readmitted VARCHAR(10) NULL,
    repaglinide VARCHAR(10) NULL,
    rosiglitazone VARCHAR(10) NULL,
    time_in_hospital INT NULL,
    tolazamide VARCHAR(10) NULL,
    tolbutamide VARCHAR(10) NULL,
    troglitazone VARCHAR(10) NULL,
    weight VARCHAR(10) NULL
                        )
                            """

CREATE_TABLE_CLEAN = """ CREATE TABLE IF NOT EXISTS diabetes_clean (
            discharge_disposition_id INT NULL,
            admission_source_id INT NULL,
            time_in_hospital INT NULL,
            num_lab_procedures INT NULL,
            num_procedures INT NULL,
            num_medications INT NULL,
            number_outpatient INT NULL,
            number_emergency INT NULL,
            number_inpatient INT NULL,
            number_diagnoses INT NULL,
            max_glu_serum INT NULL,
            A1Cresult INT NULL,
            readmitted VARCHAR(20) NULL,
            race_AfricanAmerican BOOLEAN NULL, 
            race_Asian BOOLEAN NULL,
            race_Caucasian BOOLEAN NULL,
            race_Hispanic BOOLEAN NULL,
            race_Other BOOLEAN NULL,
            gender_Female BOOLEAN NULL,
            gender_Male BOOLEAN NULL,
            `age_[0-10)` BOOLEAN NULL,
            `age_[10-20)` BOOLEAN NULL,
            `age_[20-30)` BOOLEAN NULL,
            `age_[30-40)` BOOLEAN NULL,
            `age_[40-50)` BOOLEAN NULL,
            `age_[50-60)` BOOLEAN NULL,
            `age_[60-70)` BOOLEAN NULL,
            `age_[70-80)` BOOLEAN NULL,
            `age_[80-90)` BOOLEAN NULL,
            `age_[90-100)` BOOLEAN NULL,
            cambio_Ch BOOLEAN NULL,
            cambio_No BOOLEAN NULL,
            diabetesMed_No BOOLEAN NULL,
            diabetesMed_Yes BOOLEAN NULL,
            diag_1_Circulatory BOOLEAN NULL,
            diag_1_Diabetes BOOLEAN NULL,
            diag_1_Digestive BOOLEAN NULL,
            diag_1_Genitourinary BOOLEAN NULL, 
            diag_1_Injury BOOLEAN NULL,
            diag_1_Musculoskeletal BOOLEAN NULL,
            diag_1_Neoplasms BOOLEAN NULL,
            diag_1_Other BOOLEAN NULL,
            diag_1_Respiratory BOOLEAN NULL,
            diag_2_Circulatory BOOLEAN NULL,
            diag_2_Diabetes BOOLEAN NULL,
            diag_2_Digestive BOOLEAN NULL,
            diag_2_Genitourinary BOOLEAN NULL,
            diag_2_Injury BOOLEAN NULL,
            diag_2_Musculoskeletal BOOLEAN NULL,
            diag_2_Neoplasms BOOLEAN NULL,
            diag_2_Other BOOLEAN NULL,
            diag_2_Respiratory BOOLEAN NULL,
            diag_3_Circulatory BOOLEAN NULL,
            diag_3_Diabetes BOOLEAN NULL,
            diag_3_Digestive BOOLEAN NULL,
            diag_3_Genitourinary BOOLEAN NULL, 
            diag_3_Injury BOOLEAN NULL,
            diag_3_Musculoskeletal BOOLEAN NULL,
            diag_3_Neoplasms BOOLEAN NULL,
            diag_3_Other BOOLEAN NULL,
            diag_3_Respiratory BOOLEAN NULL)"""

CREATE_TABLE_CLEAN_TRAIN = """ CREATE TABLE IF NOT EXISTS diabetes_clean_train (
            discharge_disposition_id INT NULL,
            admission_source_id INT NULL,
            time_in_hospital INT NULL,
            num_lab_procedures INT NULL,
            num_procedures INT NULL,
            num_medications INT NULL,
            number_outpatient INT NULL,
            number_emergency INT NULL,
            number_inpatient INT NULL,
            number_diagnoses INT NULL,
            max_glu_serum INT NULL,
            A1Cresult INT NULL,
            readmitted VARCHAR(20) NULL,
            race_AfricanAmerican BOOLEAN NULL, 
            race_Asian BOOLEAN NULL,
            race_Caucasian BOOLEAN NULL,
            race_Hispanic BOOLEAN NULL,
            race_Other BOOLEAN NULL,
            gender_Female BOOLEAN NULL,
            gender_Male BOOLEAN NULL,
            `age_[0-10)` BOOLEAN NULL,
            `age_[10-20)` BOOLEAN NULL,
            `age_[20-30)` BOOLEAN NULL,
            `age_[30-40)` BOOLEAN NULL,
            `age_[40-50)` BOOLEAN NULL,
            `age_[50-60)` BOOLEAN NULL,
            `age_[60-70)` BOOLEAN NULL,
            `age_[70-80)` BOOLEAN NULL,
            `age_[80-90)` BOOLEAN NULL,
            `age_[90-100)` BOOLEAN NULL,
            cambio_Ch BOOLEAN NULL,
            cambio_No BOOLEAN NULL,
            diabetesMed_No BOOLEAN NULL,
            diabetesMed_Yes BOOLEAN NULL,
            diag_1_Circulatory BOOLEAN NULL,
            diag_1_Diabetes BOOLEAN NULL,
            diag_1_Digestive BOOLEAN NULL,
            diag_1_Genitourinary BOOLEAN NULL, 
            diag_1_Injury BOOLEAN NULL,
            diag_1_Musculoskeletal BOOLEAN NULL,
            diag_1_Neoplasms BOOLEAN NULL,
            diag_1_Other BOOLEAN NULL,
            diag_1_Respiratory BOOLEAN NULL,
            diag_2_Circulatory BOOLEAN NULL,
            diag_2_Diabetes BOOLEAN NULL,
            diag_2_Digestive BOOLEAN NULL,
            diag_2_Genitourinary BOOLEAN NULL,
            diag_2_Injury BOOLEAN NULL,
            diag_2_Musculoskeletal BOOLEAN NULL,
            diag_2_Neoplasms BOOLEAN NULL,
            diag_2_Other BOOLEAN NULL,
            diag_2_Respiratory BOOLEAN NULL,
            diag_3_Circulatory BOOLEAN NULL,
            diag_3_Diabetes BOOLEAN NULL,
            diag_3_Digestive BOOLEAN NULL,
            diag_3_Genitourinary BOOLEAN NULL, 
            diag_3_Injury BOOLEAN NULL,
            diag_3_Musculoskeletal BOOLEAN NULL,
            diag_3_Neoplasms BOOLEAN NULL,
            diag_3_Other BOOLEAN NULL,
            diag_3_Respiratory BOOLEAN NULL)"""

CREATE_TABLE_CLEAN_TEST = """ CREATE TABLE IF NOT EXISTS diabetes_clean_test (
            discharge_disposition_id INT NULL,
            admission_source_id INT NULL,
            time_in_hospital INT NULL,
            num_lab_procedures INT NULL,
            num_procedures INT NULL,
            num_medications INT NULL,
            number_outpatient INT NULL,
            number_emergency INT NULL,
            number_inpatient INT NULL,
            number_diagnoses INT NULL,
            max_glu_serum INT NULL,
            A1Cresult INT NULL,
            readmitted VARCHAR(20) NULL,
            race_AfricanAmerican BOOLEAN NULL, 
            race_Asian BOOLEAN NULL,
            race_Caucasian BOOLEAN NULL,
            race_Hispanic BOOLEAN NULL,
            race_Other BOOLEAN NULL,
            gender_Female BOOLEAN NULL,
            gender_Male BOOLEAN NULL,
            `age_[0-10)` BOOLEAN NULL,
            `age_[10-20)` BOOLEAN NULL,
            `age_[20-30)` BOOLEAN NULL,
            `age_[30-40)` BOOLEAN NULL,
            `age_[40-50)` BOOLEAN NULL,
            `age_[50-60)` BOOLEAN NULL,
            `age_[60-70)` BOOLEAN NULL,
            `age_[70-80)` BOOLEAN NULL,
            `age_[80-90)` BOOLEAN NULL,
            `age_[90-100)` BOOLEAN NULL,
            cambio_Ch BOOLEAN NULL,
            cambio_No BOOLEAN NULL,
            diabetesMed_No BOOLEAN NULL,
            diabetesMed_Yes BOOLEAN NULL,
            diag_1_Circulatory BOOLEAN NULL,
            diag_1_Diabetes BOOLEAN NULL,
            diag_1_Digestive BOOLEAN NULL,
            diag_1_Genitourinary BOOLEAN NULL, 
            diag_1_Injury BOOLEAN NULL,
            diag_1_Musculoskeletal BOOLEAN NULL,
            diag_1_Neoplasms BOOLEAN NULL,
            diag_1_Other BOOLEAN NULL,
            diag_1_Respiratory BOOLEAN NULL,
            diag_2_Circulatory BOOLEAN NULL,
            diag_2_Diabetes BOOLEAN NULL,
            diag_2_Digestive BOOLEAN NULL,
            diag_2_Genitourinary BOOLEAN NULL,
            diag_2_Injury BOOLEAN NULL,
            diag_2_Musculoskeletal BOOLEAN NULL,
            diag_2_Neoplasms BOOLEAN NULL,
            diag_2_Other BOOLEAN NULL,
            diag_2_Respiratory BOOLEAN NULL,
            diag_3_Circulatory BOOLEAN NULL,
            diag_3_Diabetes BOOLEAN NULL,
            diag_3_Digestive BOOLEAN NULL,
            diag_3_Genitourinary BOOLEAN NULL, 
            diag_3_Injury BOOLEAN NULL,
            diag_3_Musculoskeletal BOOLEAN NULL,
            diag_3_Neoplasms BOOLEAN NULL,
            diag_3_Other BOOLEAN NULL,
            diag_3_Respiratory BOOLEAN NULL)"""



CREATE_TABLE_CLEAN_VAL = """ CREATE TABLE IF NOT EXISTS diabetes_clean_val (
            discharge_disposition_id INT NULL,
            admission_source_id INT NULL,
            time_in_hospital INT NULL,
            num_lab_procedures INT NULL,
            num_procedures INT NULL,
            num_medications INT NULL,
            number_outpatient INT NULL,
            number_emergency INT NULL,
            number_inpatient INT NULL,
            number_diagnoses INT NULL,
            max_glu_serum INT NULL,
            A1Cresult INT NULL,
            readmitted VARCHAR(20) NULL,
            race_AfricanAmerican BOOLEAN NULL, 
            race_Asian BOOLEAN NULL,
            race_Caucasian BOOLEAN NULL,
            race_Hispanic BOOLEAN NULL,
            race_Other BOOLEAN NULL,
            gender_Female BOOLEAN NULL,
            gender_Male BOOLEAN NULL,
            `age_[0-10)` BOOLEAN NULL,
            `age_[10-20)` BOOLEAN NULL,
            `age_[20-30)` BOOLEAN NULL,
            `age_[30-40)` BOOLEAN NULL,
            `age_[40-50)` BOOLEAN NULL,
            `age_[50-60)` BOOLEAN NULL,
            `age_[60-70)` BOOLEAN NULL,
            `age_[70-80)` BOOLEAN NULL,
            `age_[80-90)` BOOLEAN NULL,
            `age_[90-100)` BOOLEAN NULL,
            cambio_Ch BOOLEAN NULL,
            cambio_No BOOLEAN NULL,
            diabetesMed_No BOOLEAN NULL,
            diabetesMed_Yes BOOLEAN NULL,
            diag_1_Circulatory BOOLEAN NULL,
            diag_1_Diabetes BOOLEAN NULL,
            diag_1_Digestive BOOLEAN NULL,
            diag_1_Genitourinary BOOLEAN NULL, 
            diag_1_Injury BOOLEAN NULL,
            diag_1_Musculoskeletal BOOLEAN NULL,
            diag_1_Neoplasms BOOLEAN NULL,
            diag_1_Other BOOLEAN NULL,
            diag_1_Respiratory BOOLEAN NULL,
            diag_2_Circulatory BOOLEAN NULL,
            diag_2_Diabetes BOOLEAN NULL,
            diag_2_Digestive BOOLEAN NULL,
            diag_2_Genitourinary BOOLEAN NULL,
            diag_2_Injury BOOLEAN NULL,
            diag_2_Musculoskeletal BOOLEAN NULL,
            diag_2_Neoplasms BOOLEAN NULL,
            diag_2_Other BOOLEAN NULL,
            diag_2_Respiratory BOOLEAN NULL,
            diag_3_Circulatory BOOLEAN NULL,
            diag_3_Diabetes BOOLEAN NULL,
            diag_3_Digestive BOOLEAN NULL,
            diag_3_Genitourinary BOOLEAN NULL, 
            diag_3_Injury BOOLEAN NULL,
            diag_3_Musculoskeletal BOOLEAN NULL,
            diag_3_Neoplasms BOOLEAN NULL,
            diag_3_Other BOOLEAN NULL,
            diag_3_Respiratory BOOLEAN NULL)"""